### PR TITLE
Changesto namespace

### PR DESCRIPTION
**Pull request by rfeseha**

### CODE REVIEW

**Review by mdoam — COMMENTED** [review]
Hi, I think I agree with Vivian about the namespace name changed. I tried on my laptop and they are EventBriteAssignment instead of EventBriteAssignment3A. Also check about docker-compose.yml. The file shows as conflict.

**Review by vlau26 — APPROVED** [review]
I think it looks good, ready to go!

**Comment by vlau26** [comment]
i resolved the conflicts from the docker file, so it's good to merge now.

**Comment by vlau26** [comment]
if you can't un-delete the token migrations, I will add it back in once you merge

**Pull request merged**
